analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 2434084,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 2412960,\\n  \\"organizationId\\"\: 2472282,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 2412960\\n}"
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.onpremise.enable=false
analytics.testcloud.hub.switchHub.enable=false
